name: Notification workflow

on: push

jobs:
    tests:
      name: Test Project
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install dependencies
          run: |
            python -m pip3 install --upgrade pip
            pip3 install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
            pip3 install -r backend/requirements.txt
        - name: Test with flake8
          run: |
            python -m flake8
